Core Lib Documentation: `Syscalls` module
cairo-book/cairo pull request #13
Opened 2024-12-02 10:40 UTC by TAdev0

2024-12-02 13:51 UTC, enitrat requested changes
There is too much information missing, not enough context on how to use these functions, their side effects, whether they should actually be used directly or not, etc

I see you're taken some elements from https://docs.starknet.io/architecture-and-concepts/smart-contracts/system-calls-cairo1/#get_execution_info but you left out most of the interesting details.


Focus on the "how", "why", not only the "what"

2024-12-09 17:23 UTC, TAdev0 commented on corelib/src/starknet/syscalls.cairo
> +/// * `class_hash` - The class hash that should replace the current one.
yes

2024-12-09 17:24 UTC, TAdev0 commented on corelib/src/starknet/syscalls.cairo
> +/// * `class_hash` - The class hash that should replace the current one.
see new cairo campaign, middle floor part 2 :p

2024-12-09 17:29 UTC, TAdev0 commented on corelib/src/starknet/syscalls.cairo
> +/// * `input` - The input provided to the keccak function.
no. and this is already clear:

```
/// The system call does not add any padding and the input needs to be a multiple of 1088 bits
/// (== 17 u64 word).
```

2024-12-09 17:30 UTC, TAdev0 commented on corelib/src/starknet/syscalls.cairo
> +/// Returns a box containing the current V2 execution information.
indeed this syscall is better not used directly there are wrappers for it

2024-12-21 09:06 UTC, enitrat commented on corelib/src/starknet/syscalls.cairo
> +/// * `class_hash` - The class hash that should replace the current one.
> yes

well, the correct answer is actually no.

consider a contract with

```
// Original Class
fn upgrade(ref self: ContractState){
   replace_class(...);
   println!("hello")
}

// New Class
fn upgrade(ref self: ContractState){
   replace_class(...);
   println!("hello");
}
```

-> The new class is _only effective_ after the end of the current call.

so to execute new code, you'd need to return from the current call and make another call

2024-12-21 09:26 UTC, enitrat approved these changes

2024-12-21 14:42 UTC, closed without merging