Core Lib Documentation: `Metaprogramming` module
cairo-book/cairo pull request #2
Opened 2024-11-27 11:15 UTC by TAdev0

2024-11-27 15:19 UTC, enitrat requested changes

2024-11-27 15:19 UTC, enitrat commented on corelib/src/metaprogramming.cairo
> +//! Metaprogramming utilities for working with tuples.
I have no idea what this module is about after reading this 🤔

2024-11-27 15:19 UTC, enitrat commented on corelib/src/metaprogramming.cairo
>  /// Assumes that `TypeEqualImpl` is the only implementation of this trait.
This one sounds interesting. Can you make some research on that? Can it be used meaningfully outside the corelib with negative traits ?

2024-11-28 10:33 UTC, TAdev0 commented on corelib/src/metaprogramming.cairo
> +//! Metaprogramming utilities for working with tuples.
me neither

2024-11-29 04:46 UTC, enitrat commented on corelib/src/metaprogramming.cairo
>  /// Assumes that `TypeEqualImpl` is the only implementation of this trait.
the trait ensures that a type T is not equal to another type S. That's a type restriction that you can use for generic functions. 

Can you try to play with this and find a suitable use case in order to document this properly ?

2024-11-29 04:46 UTC, enitrat commented on corelib/src/metaprogramming.cairo
> +//! Metaprogramming utilities for working with tuples.
Then it's not ready for review

2024-12-09 17:20 UTC, TAdev0 commented on corelib/src/metaprogramming.cairo
>  /// Assumes that `TypeEqualImpl` is the only implementation of this trait.
just spent an hour on it. I dont understand what i can do with it:

```
fn always_true<T, U, + Drop<T>, + Drop<U>, + TypeEqual<T, T>>(x: T, y: U) -> bool {
    true
}
```

this doesnt bring anything, adding a constrain that `T` is of same type as `T` doesnt make sense.

and 

```
fn always_true<T, U, + Drop<T>, + Drop<U>, + TypeEqual<T, U>>(x: T, y: U) -> bool {
    true
}
```

doest compile with Type mismatch: `U` and `T`.

I dont know what i can do with that trait

2024-12-21 12:38 UTC, enitrat commented on corelib/src/metaprogramming.cairo
>  /// Assumes that `TypeEqualImpl` is the only implementation of this trait.
an example:

```rust
use core::metaprogramming::TypeEqual;

/// A simple pair container that requires two different types.
/// Useful for representing relationships between distinct items.
struct TypePair<T, U> {
    first: T,
    second: U,
}


pub trait TypePairTrait<T, U> {
    fn new(first: T, second: U) -> TypePair<T, U>;
}

/// Implementation only allowed when T and U are different types
impl TypePairImpl<T, U, -TypeEqual<T, U>, +Drop<T>, +Drop<U>> of TypePairTrait<T, U> {
    fn new(first: T, second: U) -> TypePair<T, U> {
        TypePair {
            first: first,
            second: second
        }
    }
}

fn main() {
    // This works - different types
    let number_and_bool: TypePair<u32, bool> = TypePairTrait::new(1, true);

    // This fails to compile - same types not allowed
    let number_and_number: TypePair<u32, u32> = TypePairTrait::new(1, 2);
}

```

2025-01-03 15:41 UTC, TAdev0 commented on corelib/src/metaprogramming.cairo
>  /// Assumes that `TypeEqualImpl` is the only implementation of this trait.
okkkk no i understand the feature, its actually usable only as a negative impl , i cannot constraint 2 generic types `T and `U` to be of the same type, given that only one impl of TypeEqual exists, ie `impl TypeEqualImpl<T> of TypeEqual<T, T>;` 

all clear now, thanks!

2025-01-03 15:52 UTC, TAdev0 commented
@enitrat  ready for review

2025-01-05 13:01 UTC, enitrat commented on corelib/src/metaprogramming.cairo
> +///     let number_and_number: TypePair<u32, u32> = TypePairTrait::new(1, 2);
```suggestion
///     // let number_and_number: TypePair<u32, u32> = TypePairTrait::new(1, 2);
```

2025-01-05 13:01 UTC, enitrat approved these changes

2025-01-05 15:23 UTC, closed without merging