Core Lib Documentation: `ContractAddress` module
cairo-book/cairo pull request #22
Opened 2024-12-02 11:41 UTC by TAdev0

2024-12-09 16:56 UTC, TAdev0 commented
ready for review

2024-12-20 16:37 UTC, enitrat requested changes

2024-12-20 16:37 UTC, enitrat commented on corelib/src/starknet/contract_address.cairo
> +//! [`Zero`], [`PartialEq`], [`PartialOrd`] and [`Debug`].
```suggestion
```

2024-12-20 16:37 UTC, enitrat commented on corelib/src/starknet/contract_address.cairo
> +//! `felt252` value.
```suggestion
//! A variable of type `ContractAddress` can be created from a `felt252` value using the `contract_address_const` function, or using the `TryInto` trait.
```

+ the change will likely require format

2024-12-20 16:37 UTC, enitrat commented on corelib/src/starknet/contract_address.cairo
> +/// Returns a `ContractAddress` value given a `felt252` address value.
```suggestion
/// Returns a `ContractAddress` given a `felt252` value.
```

2025-01-03 15:16 UTC, TAdev0 commented
@enitrat  ready for review

2025-01-04 11:39 UTC, closed without merging