Core Lib Documentation:  `Index` module
cairo-book/cairo pull request #30
Opened 2024-12-02 12:32 UTC by TAdev0

2024-12-02 16:00 UTC, enitrat requested changes
see https://doc.rust-lang.org/src/core/ops/index.rs.html#58

2024-12-02 16:00 UTC, enitrat commented on corelib/src/ops/index.cairo
> +/// A trait for a view of an item contained in type `C` with an index of type `I`.
mention the `[ ]` operator at the trait level

2024-12-02 16:01 UTC, enitrat commented on corelib/src/ops/index.cairo
> +/// A trait for a view of an item contained in type `C` with an index of type `I`.
mention that it should not be implemented if Index already exists on that type and vice versa

2024-12-02 16:19 UTC, TAdev0 commented on corelib/src/ops/index.cairo
> +/// A trait for a view of an item contained in type `C` with an index of type `I`.
addressed @enitrat

2024-12-03 03:36 UTC, enitrat commented on corelib/src/ops/index.cairo
> +/// A trait for a view of an item contained in type `C` with an index of type `I`.
this still gives no insights on the reasons I should implement a trait and not the other

2024-12-03 03:55 UTC, enitrat commented on corelib/src/ops/index.cairo
> +/// A trait for a view of an item contained in type `C` with an index of type `I`.
and no actionable example :(

2024-12-03 03:59 UTC, enitrat approved these changes
I was expecting something more like this

2024-12-09 15:36 UTC, closed without merging