Core Lib Documentation: `Range` module
cairo-book/cairo pull request #31
Opened 2024-12-02 12:39 UTC by TAdev0

2024-12-05 13:17 UTC, enitrat requested changes
more doc please

https://doc.rust-lang.org/src/core/ops/range.rs.html#80

2024-12-09 15:30 UTC, TAdev0 commented
@enitrat  i added 2 lines but i dont see what to do add more. Feel free to add things if you'd like

2024-12-20 20:28 UTC, enitrat commented
The current doc is not saying what the ".." operator is and what "range" is

2025-01-03 17:35 UTC, TAdev0 commented
@enitrat  ready for review

2025-01-04 00:21 UTC, enitrat commented
please rebase to bring the latest changes

2025-01-05 12:50 UTC, enitrat commented on corelib/src/ops/range.cairo
> +pub(crate) impl RangeOpImpl<T> of RangeOp<T> {
je me suis permis de modifier la visibilité car ceci ne devrait pas etre accessible à l'exterieur

2025-01-05 12:50 UTC, enitrat approved these changes

2025-01-05 15:27 UTC, closed without merging