Core Lib Documentation: `Traits` module
cairo-book/cairo pull request #40
Opened 2024-12-02 13:35 UTC by TAdev0

2025-01-03 20:03 UTC, TAdev0 commented
@enitrat ready for review

2025-01-03 22:16 UTC, enitrat requested changes

2025-01-03 22:16 UTC, enitrat commented on corelib/src/traits.cairo
> +/// A trait for comparing two values of the same type.
please synchronize all trait documentations with Rust's equivalents

2025-01-07 16:35 UTC, TAdev0 commented on corelib/src/traits.cairo
> +/// A trait for comparing two values of the same type.
yep, done

2025-01-07 16:35 UTC, TAdev0 commented
@enitrat  ready for review

2025-01-10 22:23 UTC, enitrat requested changes
Missing proper doc for some traits like `Sub`, `Div`, `Mul`, `Bit*`, `Into`, `TryInto`, etc.
Don't reinvent the wheel: https://doc.rust-lang.org/src/core/ops/arith.rs.html#185
https://doc.rust-lang.org/src/core/ops/bit.rs.html#144

see example pushed

2025-01-11 16:35 UTC, TAdev0 commented
@enitrat  i think we should be good now. Didnt get that you wanted a custom impl for each trait in trait level doc

2025-01-12 13:36 UTC, enitrat commented
@TAdev0 for review of last changes

2025-01-12 14:43 UTC, TAdev0 commented
seems all good i guess

2025-01-12 14:45 UTC, enitrat approved these changes
don't guess, ensure it is :)

2025-01-12 14:48 UTC, closed without merging