Core Lib Documentation: `Lib` module
cairo-book/cairo pull request #41
Opened 2024-12-02 13:41 UTC by TAdev0

2024-12-23 16:13 UTC, enitrat commented on corelib/src/lib.cairo
> +///
what happens if you divide 3 by 2 ?

2024-12-23 16:16 UTC, enitrat requested changes

2024-12-23 16:16 UTC, enitrat commented on corelib/src/lib.cairo
> +    /// Returns the default value for a `felt252`, i.e., 0.
```suggestion
```

2024-12-23 16:16 UTC, enitrat commented on corelib/src/lib.cairo
> +    /// Returns the default value for dictionary `felt252` values, i.e., 0.
```suggestion
```

2024-12-23 16:16 UTC, enitrat commented on corelib/src/lib.cairo
> +/// Box module.
```suggestion
```

remove these doc lines. the module doc is sufficient

2024-12-23 16:16 UTC, enitrat commented on corelib/src/lib.cairo
> +/// `felt252` is the basic field element used in Cairo.
Deserves more doc than that, especially on edge-case behaviors

2024-12-23 16:16 UTC, enitrat commented on corelib/src/lib.cairo
> +    /// Returns the default value for dictionary `bool` values, i.e., `false`.
```suggestion
```

2025-01-03 18:26 UTC, TAdev0 commented on corelib/src/lib.cairo
> +///
weird stuff happens :p

2025-01-03 18:34 UTC, TAdev0 commented
@enitrat  i removed all the redundant comments that describe imported modules.

Added a few comments on felt252 type, not sure how deep you wanna go given that everything is in the cairo book

2025-01-03 22:02 UTC, enitrat commented on corelib/src/lib.cairo
> +/// 1206167596222043737899107594365023368541035738443865566657697352045290673495);
document this strange behavior

2025-01-04 11:35 UTC, TAdev0 commented on corelib/src/lib.cairo
> +/// 1206167596222043737899107594365023368541035738443865566657697352045290673495);
done

2025-01-04 11:37 UTC, closed without merging